apiVersion: v1
kind: Secret
metadata:
  name: aplus-init-secrets
  annotations:
    "helm.sh/hook": "pre-install"
data:
  POSTGRES_PASSWORD: {{ default (randAlphaNum 20) .Values.dbPassword | b64enc | quote }}
  SECRET_KEY: {{ default (randAlphaNum 30) .Values.secretKey | b64enc | quote }}
