# Required for A+ to accept grading results
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aplus-read-pods
subjects:
- kind: ServiceAccount
  name: aplus-sa
roleRef:
  kind: Role
  name: read-pods
  apiGroup: rbac.authorization.k8s.io
