---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/log"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-namespace-pods
subjects:
- kind: ServiceAccount
  name: grader-sa
roleRef:
  kind: Role
  name: manage-pods
  apiGroup: rbac.authorization.k8s.io
