apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
{{ (.Files.Glob "files/auth/*").AsConfig | indent 2 }}
